from .SequentialLearningPatternManager import SequentialLearningPatternManager
from .TaskPatternManager import TaskPatternManager

from . import PatternDistanceFunction
from . import PatternGenerators